filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

  - type: filestream
    paths:
      - /applogs/*/*.log
      - /applogs/*/workers-artifacts/*/*/*.log*

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:localhost:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
